### ISSUE TITLE
TeamCity build link broken

### ISSUE THREAD

**Issue by DonatasNasdaq** [gradle/gradle-enterprise-build-config-samples#101]
TeamCity build number is not necessarily a number; for our projects it is a number plus git hash. Yet CustomBuildScanEnhancements.java expects it to be only number and this results in error:
```
org.apache.maven.InternalErrorException: Internal error: com.gradle.scan.plugin.b: Build scan custom link url must be a well-formed http, https, or mailto URL (name: TeamCity build, value: http://bvteamcity02.org.nasdaqomx.com:8111/viewLog.html?buildNumber=11612 [8e26a27]&buildTypeId=Ncsd_NcsdSolution_Core_MonoBuild_Backend).
```
because for this project buildNumber is "11612 [8e26a27]"

May I suggest to use buildId instead of buildNumber? Our TeamCity (v2020.2.2) in its GUI forms links like this:
```https://bvteamcity02.org.nasdaqomx.com/viewLog.html?buildId=5271771v&buildTypeId=Ncsd_NcsdSolution_Core_MonoBuild_Backend```

You could retrieve buildId this way:
```Optional<String> buildId = projectProperty(mavenSession, "teamcity.build.id");```
#104

**Comment by DonatasNasdaq** [comment]
Pull-request:
https://github.com/gradle/gradle-enterprise-build-config-samples/pull/102

**Comment by jthurne** [comment]
@DonatasNasdaq thanks for reporting this issue and opening the PR!

Ultimately, we decided to properly encode the buildNumber rather than using the build id, partly because it was a lower-risk change, and partly because we have a recollection where build ID proved not to be as universally unique as we had assumed.

We'll release a new version of this plugin early next week.
