### ISSUE TITLE
Should capture TEAMCITY_BUILDCONF_NAME

### ISSUE THREAD

**Issue by oehme** [gradle/gradle-enterprise-build-config-samples#74]
This variable contains the name of the current build configuration. E.g. `Gradle_Master_Check_SanityCheck` and could be used to quickly filter for the performance of just that particular stage.

**Comment by etiennestuder** [comment]
@oehme Thanks. Not forgotten. We will look into it soon.

**Comment by bigdaz** [comment]
It turns out that `TEAMCITY_BUILDCONF_NAME` is not sufficient, since this only identifies the configuration name (eg `SanityCheck`) and not the project that the configuration belongs to (eg `Gradle_Master_Check`).

Using `teamcity.buildType.id` provides the [External ID](https://www.jetbrains.com/help/teamcity/identifier.html#External+IDs) for the build configuration, which includes the project hierarchy and configuration name, like `Gradle_Master_Check_SanityCheck`.
